apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis-podmonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: redis
  namespaceSelector:
    matchNames:
      - voting-app
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s