{
 "title": "SRE Dashboard",
 "time": { "from": "2026-04-15T20:42:08.000Z", "to": "2026-04-15T20:47:08.000Z" },
 "panels": [
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"votes\"}[5m])",
     "legendFormat": "ops"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"votes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"votes\"} / 1024 / 1024",
     "legendFormat": "database_size"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Redis - Queue Size (votes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "redis_db_keys{db=\"db0\"}",
     "legendFormat": "Queue "
    }
   ]
  },
  {
   "title": "Redis - Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes / 1024 / 1024",
     "legendFormat": "used_bytes"
    }
   ]
  },
  {
   "title": "Redis - Connected Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  { "title": "Бизнес-метрика", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Votes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "sum(rate(votes_total[5m]))", "legendFormat": "votes_total" }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Worker - Processed per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(worker_processed_total[5m])",
     "legendFormat": "ops"
    }
   ]
  },
  {
   "title": "Worker - Errors per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(worker_errors_total[5m])", "legendFormat": "__auto" }
   ]
  },
  { "title": "Result UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Result UI - Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{container=\"result\", route=\"/\"}[5m])) by (le))",
     "legendFormat": "Latency "
    }
   ]
  },
  {
   "title": "Result UI - Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{container=\"result\", method=\"GET\", route=\"/\", status_code=\"200\"}[5m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Result UI - Error Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{container=\"result\", status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{container=\"result\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Vote UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Vote UI - Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{container=\"vote\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "Latency "
    }
   ]
  },
  {
   "title": "Vote UI - Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{container=\"vote\", method=\"POST\", status=\"200\"}[5m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Vote UI - Error Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{container=\"vote\", status=~\"5..\"}[5m])) / sum(rate(http_requests_total{container=\"vote\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU&Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Memory Usage (% от лимита)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"voting-app\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"voting-app\", resource=\"memory\"}) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (% от лимита)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"voting-app\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"voting-app\", resource=\"cpu\"}) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Доступность", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Result UI - Доступность (SLO 99.5%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"voting-app\", phase=\"Running\", pod=~\"result.*\"}) / sum(kube_deployment_status_replicas{namespace=\"voting-app\", deployment=\"result\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker - Доступность (SLO 99.9%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"voting-app\", phase=\"Running\", pod=~\"worker.*\"}) / sum(kube_deployment_status_replicas{namespace=\"voting-app\", deployment=\"worker\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vote UI - Доступность (SLO 99.9%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"voting-app\", phase=\"Running\", pod=~\"vote.*\"}) / sum(kube_deployment_status_replicas{namespace=\"voting-app\", deployment=\"vote\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis - Доступность (SLO 99.99%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"voting-app\", phase=\"Running\", pod=~\"redis.*\"}) / 1 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL - Доступность (SLO 99.99%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"voting-app\", phase=\"Running\", pod=~\"db.*\"}) / 1 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Проблемы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Рестарты",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"voting-app\"}[24h])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Статусы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Статусы",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"voting-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}